install.packages("devtools")
install.packages("remotes")
remotes::install_version("SDMTools", "1.1-221")
devtools::install_github("statsbomb/StatsBombR")
library(tidyverse)
library(StatsBombR)
FreeCompetitions()
